#!/usr/bin/env python3
"""generate_nav_map.py — the module/section map the secondary header reads.

The header shows one item per module, each opening a menu of that module's
sections. Those sections are not a second list somebody maintains by hand;
they are read out of the pages themselves, so the menu cannot drift from the
headings it points at.

A section is a `<section class="topic-group" id="section-N-M">` whose
`<h2 id="section-N-M-title">` carries a `.topic-section__number` span and the
title text. That is the structure AUTHORING-CONTRACT.md §4.1 already requires,
so nothing new is being asked of an author.

Output is `assets/js/nav-map.js`, a classic script publishing `window.NAV_MAP`.
Not JSON: `fetch()` is blocked under `file://`, and the whole point is that the
dashboard works when you open the folder.

    python3 tools/generate_nav_map.py [--check]
"""

from __future__ import annotations

import argparse
import html as html_mod
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "js" / "nav-map.js"

# (file, module label, short label, module name). Order is header order.
CHAPTERS = [
    ("m0-foundations.html", "Module 0", "M0", "Foundations & Tooling"),
    ("m1-algorithm-design.html", "Module 1", "M1", "Algorithm Design & Analysis"),
    ("m2-probability.html", "Module 2", "M2", "Probability & Random Processes"),
    ("m3-graphs.html", "Module 3", "M3", "Graphs"),
    ("m4-image-processing.html", "Module 4", "M4", "Image Processing"),
    ("m5-data-mining.html", "Module 5", "M5", "Data Mining"),
    ("m6-computational-geometry.html", "Module 6", "M6", "Computational Geometry"),
    ("m7-discrete-optimization.html", "Module 7", "M7", "Discrete Optimization"),
]

THREADS = [
    ("cross-cutting/exam-practice.html", "Exam practice by problem type"),
    ("cross-cutting/complexity-comparator.html", "Thread: complexity comparator"),
    ("cross-cutting/greedy-gallery.html", "Thread: greedy gallery"),
    ("cross-cutting/kmeans-everywhere.html", "Thread: k-means everywhere"),
    ("cross-cutting/delaunay-thread.html", "Thread: Delaunay triangulation"),
]

GROUP_RE = re.compile(
    r'<section class="topic-group" id="(?P<id>section-[\w-]+)"'
    r'.*?<h2 id="(?P=id)-title">\s*'
    r'(?:<span class="topic-section__number">(?P<num>[^<]*)</span>)?\s*'
    r'(?P<title>[^<]*?)\s*</h2>',
    re.S,
)

TOPIC_COUNT_RE = re.compile(r'<section class="topic-section" id="topic-')


def sections_of(path: Path) -> list[dict]:
    html = path.read_text(encoding="utf-8")
    out = []
    for m in GROUP_RE.finditer(html):
        # Count the topics inside this group, for the menu's "N topics" note.
        start = m.end()
        nxt = html.find('<section class="topic-group"', start)
        chunk = html[start: nxt if nxt != -1 else len(html)]
        out.append({
            "id": m.group("id"),
            "number": (m.group("num") or "").strip(),
            # Headings are authored as HTML, so "&amp;" is what the source
            # says. The menu builds text nodes, which would print the entity
            # literally; unescape once here rather than in the browser.
            "title": html_mod.unescape(re.sub(r"\s+", " ", m.group("title")).strip()),
            "topics": len(TOPIC_COUNT_RE.findall(chunk)),
        })
    return out


def build() -> dict:
    chapters = []
    for file, label, short, name in CHAPTERS:
        path = ROOT / file
        if not path.exists():
            raise SystemExit(f"generate_nav_map: missing {file}")
        sections = sections_of(path)
        if not sections:
            raise SystemExit(
                f"generate_nav_map: {file} has no <section class=\"topic-group\"> "
                "with a matching h2 — the header menu would be empty."
            )
        chapters.append({
            "file": file,
            "label": label,
            "short": short,
            "name": name,
            "sections": sections,
        })

    threads = [
        {"file": f, "title": t}
        for f, t in THREADS
        if (ROOT / f).exists()
    ]
    return {"chapters": chapters, "threads": threads}


BANNER = """/* Classic script (no ES modules) — GENERATED by tools/generate_nav_map.py.
   Do not edit by hand; your changes will be overwritten.

   The chapter/section map the secondary header builds its dropdowns from.
   Regenerate after adding or renaming a topic group:

       python3 tools/generate_nav_map.py
*/
"""


def render(data: dict) -> str:
    body = json.dumps(data, indent=2, ensure_ascii=False)
    return f"{BANNER}window.NAV_MAP = {body};\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    data = build()
    text = render(data)
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None

    total = sum(len(c["sections"]) for c in data["chapters"])
    print(f"  nav-map      {len(data['chapters'])} modules, {total} sections, "
          f"{len(data['threads'])} threads")

    if current == text:
        print("  nav-map.js already current")
        return 0
    if args.check:
        print("  nav-map.js is STALE — run tools/generate_nav_map.py", file=sys.stderr)
        return 1
    OUT.write_text(text, encoding="utf-8")
    print(f"  wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
